'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

/* ─── Supported Languages ─────────────────────────────────────── */
export type LangCode = 'en' | 'ur' | 'ar' | 'zh' | 'fr' | 'de' | 'es' | 'hi' | 'pt' | 'ru' | 'ja' | 'ko';

export interface Language {
  code: LangCode;
  name: string;
  nativeName: string;
  flag: string;
  rtl: boolean;
}

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English',    nativeName: 'English',    flag: '🇺🇸', rtl: false },
  { code: 'ur', name: 'Urdu',       nativeName: 'اردو',        flag: '🇵🇰', rtl: true  },
  { code: 'ar', name: 'Arabic',     nativeName: 'العربية',     flag: '🇸🇦', rtl: true  },
  { code: 'zh', name: 'Chinese',    nativeName: '中文',         flag: '🇨🇳', rtl: false },
  { code: 'fr', name: 'French',     nativeName: 'Français',    flag: '🇫🇷', rtl: false },
  { code: 'de', name: 'German',     nativeName: 'Deutsch',     flag: '🇩🇪', rtl: false },
  { code: 'es', name: 'Spanish',    nativeName: 'Español',     flag: '🇪🇸', rtl: false },
  { code: 'hi', name: 'Hindi',      nativeName: 'हिंदी',        flag: '🇮🇳', rtl: false },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português',   flag: '🇧🇷', rtl: false },
  { code: 'ru', name: 'Russian',    nativeName: 'Русский',     flag: '🇷🇺', rtl: false },
  { code: 'ja', name: 'Japanese',   nativeName: '日本語',        flag: '🇯🇵', rtl: false },
  { code: 'ko', name: 'Korean',     nativeName: '한국어',        flag: '🇰🇷', rtl: false },
];

/* ─── All Translations ────────────────────────────────────────── */
export interface Translations {
  // Header / Search
  searchPlaceholder: string;
  searchNoResults: string;

  // Sidebar categories
  allTools: string;
  catText: string;
  catImage: string;
  catAudio: string;
  catVideo: string;
  catCode: string;
  catPDF: string;
  catUnit: string;
  catOthers: string;

  // Page headings
  allToolsHeading: string;
  toolsHeading: string; // "{category} Tools"

  // Tool names
  toolBgRemover: string;
  toolBeatSync: string;
  toolWordCounter: string;
  toolImageResizer: string;
  toolAiUpscaler: string;
  toolJsonFormatter: string;
  toolPdfMerger: string;
  toolUnitConverter: string;
  toolRandomGenerator: string;
  toolExcelEngine: string;
  toolPromptMatrix: string;
  toolDocIntegrity: string;
  toolAudioTranscriber: string;

  // Tool descriptions
  descBgRemover: string;
  descBeatSync: string;
  descWordCounter: string;
  descImageResizer: string;
  descAiUpscaler: string;
  descJsonFormatter: string;
  descPdfMerger: string;
  descUnitConverter: string;
  descRandomGenerator: string;
  descExcelEngine: string;
  descPromptMatrix: string;
  descDocIntegrity: string;
  descAudioTranscriber: string;

  // Common UI
  close: string;
  open: string;
  upload: string;
  download: string;
  clear: string;
  copy: string;
  copied: string;
  process: string;
  processing: string;
  reset: string;
  generate: string;
  merge: string;
  convert: string;
  analyze: string;
  compare: string;
  transcribe: string;
  remove: string;
  format: string;
  beautify: string;
  minify: string;
  validate: string;
  success: string;
  error: string;
  loading: string;
  dragDrop: string;
  or: string;
  browse: string;
  selectFile: string;
  noFile: string;
  fileReady: string;
  fileSize: string;
  fileType: string;
  output: string;
  input: string;
  result: string;
  settings: string;
  language: string;
}

/* ─── Translation Map ─────────────────────────────────────────── */
const translations: Record<LangCode, Translations> = {
  en: {
    searchPlaceholder: 'Search tools…',
    searchNoResults: 'No tools found for',
    allTools: 'All Tools',
    catText: 'Text',
    catImage: 'Image',
    catAudio: 'Audio',
    catVideo: 'Video',
    catCode: 'Code',
    catPDF: 'PDF',
    catUnit: 'Unit',
    catOthers: 'Others',
    allToolsHeading: 'All Tools',
    toolsHeading: 'Tools',
    toolBgRemover: 'AI BG Remover',
    toolBeatSync: 'BeatSync Engine',
    toolWordCounter: 'Word Counter',
    toolImageResizer: 'Image Resizer',
    toolAiUpscaler: 'AI Upscaler',
    toolJsonFormatter: 'JSON Formatter',
    toolPdfMerger: 'PDF Merger',
    toolUnitConverter: 'Unit Converter',
    toolRandomGenerator: 'Random Generator',
    toolExcelEngine: 'Excel Data Engine',
    toolPromptMatrix: 'Prompt Matrix',
    toolDocIntegrity: 'Text Integrity Engine',
    toolAudioTranscriber: 'Audio to Text',
    descBgRemover: 'Remove backgrounds from images instantly using AI.',
    descBeatSync: 'Calculate exact video cut-points based on music BPM & FPS.',
    descWordCounter: 'Count words, characters, sentences and paragraphs instantly.',
    descImageResizer: 'Resize images to exact dimensions while preserving quality.',
    descAiUpscaler: 'Enhance image quality using local AI.',
    descJsonFormatter: 'Beautify, validate, and minify JSON with syntax highlighting.',
    descPdfMerger: 'Combine multiple PDF files into a single document seamlessly.',
    descUnitConverter: 'Convert between 100+ units of length, weight, and more.',
    descRandomGenerator: 'Generate passwords, UUIDs, and lorem ipsum on demand.',
    descExcelEngine: 'Analyze, clean and process spreadsheet data with efficiency.',
    descPromptMatrix: 'Neural hierarchical prompt engineering suite for NPU models.',
    descDocIntegrity: 'Perform forensic document comparison and text analysis.',
    descAudioTranscriber: 'Transcribe any audio file into clean text 100% locally in your browser.',
    close: 'Close',
    open: 'Open',
    upload: 'Upload',
    download: 'Download',
    clear: 'Clear',
    copy: 'Copy',
    copied: 'Copied!',
    process: 'Process',
    processing: 'Processing…',
    reset: 'Reset',
    generate: 'Generate',
    merge: 'Merge',
    convert: 'Convert',
    analyze: 'Analyze',
    compare: 'Compare',
    transcribe: 'Transcribe',
    remove: 'Remove',
    format: 'Format',
    beautify: 'Beautify',
    minify: 'Minify',
    validate: 'Validate',
    success: 'Success',
    error: 'Error',
    loading: 'Loading…',
    dragDrop: 'Drag & drop file here',
    or: 'or',
    browse: 'Browse',
    selectFile: 'Select File',
    noFile: 'No file selected',
    fileReady: 'File ready',
    fileSize: 'File Size',
    fileType: 'File Type',
    output: 'Output',
    input: 'Input',
    result: 'Result',
    settings: 'Settings',
    language: 'Language',
  },

  ur: {
    searchPlaceholder: 'ٹولز تلاش کریں…',
    searchNoResults: 'کوئی ٹول نہیں ملا',
    allTools: 'تمام ٹولز',
    catText: 'متن',
    catImage: 'تصویر',
    catAudio: 'آڈیو',
    catVideo: 'ویڈیو',
    catCode: 'کوڈ',
    catPDF: 'پی ڈی ایف',
    catUnit: 'اکائی',
    catOthers: 'دیگر',
    allToolsHeading: 'تمام ٹولز',
    toolsHeading: 'ٹولز',
    toolBgRemover: 'اے آئی بیک گراؤنڈ ریموور',
    toolBeatSync: 'بیٹ سنک انجن',
    toolWordCounter: 'الفاظ گنتی',
    toolImageResizer: 'تصویر ری سائزر',
    toolAiUpscaler: 'اے آئی اپ اسکیلر',
    toolJsonFormatter: 'جے ایس او این فارمیٹر',
    toolPdfMerger: 'پی ڈی ایف مرجر',
    toolUnitConverter: 'اکائی کنورٹر',
    toolRandomGenerator: 'رینڈم جنریٹر',
    toolExcelEngine: 'ایکسل ڈیٹا انجن',
    toolPromptMatrix: 'پرامپٹ میٹرکس',
    toolDocIntegrity: 'متن سالمیت انجن',
    toolAudioTranscriber: 'آڈیو سے متن',
    descBgRemover: 'اے آئی کے ذریعے تصویروں سے پس منظر فوری طور پر ہٹائیں۔',
    descBeatSync: 'موسیقی BPM اور FPS کی بنیاد پر ویڈیو کٹ پوائنٹس درست حساب کریں۔',
    descWordCounter: 'الفاظ، حروف، جملے اور پیراگراف فوری گنیں۔',
    descImageResizer: 'معیار برقرار رکھتے ہوئے تصاویر کو مخصوص جہتوں میں تبدیل کریں۔',
    descAiUpscaler: 'مقامی اے آئی کے ذریعے تصویر کا معیار بہتر کریں۔',
    descJsonFormatter: 'نحوی نمایاں کاری کے ساتھ JSON کو خوبصورت، درست، اور چھوٹا کریں۔',
    descPdfMerger: 'متعدد PDF فائلوں کو بغیر رکاوٹ ایک دستاویز میں یکجا کریں۔',
    descUnitConverter: '100 سے زیادہ اکائیوں کے درمیان تبدیل کریں۔',
    descRandomGenerator: 'پاس ورڈ، UUID اور لوریم اپسم مطالبے پر تیار کریں۔',
    descExcelEngine: 'اسپریڈ شیٹ ڈیٹا کو مؤثر طریقے سے تجزیہ، صاف اور پروسیس کریں۔',
    descPromptMatrix: 'NPU ماڈلز کے لیے نیورل درجہ بندی پرامپٹ انجینئرنگ سوٹ۔',
    descDocIntegrity: 'فرانزک دستاویز موازنہ اور متن تجزیہ انجام دیں۔',
    descAudioTranscriber: 'کسی بھی آڈیو فائل کو آپ کے براؤزر میں 100٪ مقامی طور پر صاف متن میں تبدیل کریں۔',
    close: 'بند کریں',
    open: 'کھولیں',
    upload: 'اپ لوڈ',
    download: 'ڈاؤن لوڈ',
    clear: 'صاف کریں',
    copy: 'کاپی',
    copied: 'کاپی ہو گیا!',
    process: 'پروسیس',
    processing: 'پروسیسنگ…',
    reset: 'ری سیٹ',
    generate: 'تیار کریں',
    merge: 'ملائیں',
    convert: 'تبدیل کریں',
    analyze: 'تجزیہ کریں',
    compare: 'موازنہ کریں',
    transcribe: 'تحریر کریں',
    remove: 'ہٹائیں',
    format: 'فارمیٹ',
    beautify: 'خوبصورت کریں',
    minify: 'چھوٹا کریں',
    validate: 'تصدیق کریں',
    success: 'کامیاب',
    error: 'خرابی',
    loading: 'لوڈ ہو رہا ہے…',
    dragDrop: 'فائل یہاں ڈریگ اور ڈراپ کریں',
    or: 'یا',
    browse: 'براؤز کریں',
    selectFile: 'فائل منتخب کریں',
    noFile: 'کوئی فائل منتخب نہیں',
    fileReady: 'فائل تیار ہے',
    fileSize: 'فائل سائز',
    fileType: 'فائل قسم',
    output: 'آؤٹ پٹ',
    input: 'ان پٹ',
    result: 'نتیجہ',
    settings: 'ترتیبات',
    language: 'زبان',
  },

  ar: {
    searchPlaceholder: 'البحث عن الأدوات…',
    searchNoResults: 'لم يتم العثور على أدوات',
    allTools: 'جميع الأدوات',
    catText: 'نص',
    catImage: 'صورة',
    catAudio: 'صوت',
    catVideo: 'فيديو',
    catCode: 'كود',
    catPDF: 'PDF',
    catUnit: 'وحدة',
    catOthers: 'أخرى',
    allToolsHeading: 'جميع الأدوات',
    toolsHeading: 'أدوات',
    toolBgRemover: 'إزالة الخلفية بالذكاء الاصطناعي',
    toolBeatSync: 'محرك BeatSync',
    toolWordCounter: 'عداد الكلمات',
    toolImageResizer: 'تغيير حجم الصورة',
    toolAiUpscaler: 'تحسين الصورة بالذكاء الاصطناعي',
    toolJsonFormatter: 'منسق JSON',
    toolPdfMerger: 'دمج PDF',
    toolUnitConverter: 'محول الوحدات',
    toolRandomGenerator: 'المولد العشوائي',
    toolExcelEngine: 'محرك بيانات Excel',
    toolPromptMatrix: 'مصفوفة الأوامر',
    toolDocIntegrity: 'محرك سلامة النص',
    toolAudioTranscriber: 'تحويل الصوت إلى نص',
    descBgRemover: 'إزالة خلفيات الصور فوراً باستخدام الذكاء الاصطناعي.',
    descBeatSync: 'احسب نقاط قطع الفيديو الدقيقة بناءً على BPM و FPS.',
    descWordCounter: 'عد الكلمات والأحرف والجمل والفقرات فوراً.',
    descImageResizer: 'تغيير حجم الصور إلى أبعاد محددة مع الحفاظ على الجودة.',
    descAiUpscaler: 'تحسين جودة الصورة باستخدام الذكاء الاصطناعي المحلي.',
    descJsonFormatter: 'تجميل وتحقق وتصغير JSON مع تمييز الصيغة.',
    descPdfMerger: 'دمج ملفات PDF متعددة في مستند واحد بسلاسة.',
    descUnitConverter: 'التحويل بين أكثر من 100 وحدة قياس.',
    descRandomGenerator: 'إنشاء كلمات مرور و UUID و lorem ipsum عند الطلب.',
    descExcelEngine: 'تحليل وتنظيف ومعالجة بيانات جداول البيانات بكفاءة.',
    descPromptMatrix: 'مجموعة هندسة الأوامر الهرمية العصبية لنماذج NPU.',
    descDocIntegrity: 'إجراء مقارنة جنائية للمستندات وتحليل النصوص.',
    descAudioTranscriber: 'تحويل أي ملف صوتي إلى نص نظيف محلياً 100% في متصفحك.',
    close: 'إغلاق',
    open: 'فتح',
    upload: 'رفع',
    download: 'تحميل',
    clear: 'مسح',
    copy: 'نسخ',
    copied: 'تم النسخ!',
    process: 'معالجة',
    processing: 'جاري المعالجة…',
    reset: 'إعادة تعيين',
    generate: 'إنشاء',
    merge: 'دمج',
    convert: 'تحويل',
    analyze: 'تحليل',
    compare: 'مقارنة',
    transcribe: 'نسخ',
    remove: 'إزالة',
    format: 'تنسيق',
    beautify: 'تجميل',
    minify: 'تصغير',
    validate: 'تحقق',
    success: 'نجاح',
    error: 'خطأ',
    loading: 'جاري التحميل…',
    dragDrop: 'اسحب وأفلت الملف هنا',
    or: 'أو',
    browse: 'تصفح',
    selectFile: 'اختر ملفاً',
    noFile: 'لم يتم اختيار ملف',
    fileReady: 'الملف جاهز',
    fileSize: 'حجم الملف',
    fileType: 'نوع الملف',
    output: 'الإخراج',
    input: 'الإدخال',
    result: 'النتيجة',
    settings: 'الإعدادات',
    language: 'اللغة',
  },

  zh: {
    searchPlaceholder: '搜索工具…',
    searchNoResults: '未找到相关工具',
    allTools: '所有工具',
    catText: '文本',
    catImage: '图像',
    catAudio: '音频',
    catVideo: '视频',
    catCode: '代码',
    catPDF: 'PDF',
    catUnit: '单位',
    catOthers: '其他',
    allToolsHeading: '所有工具',
    toolsHeading: '工具',
    toolBgRemover: 'AI 背景去除',
    toolBeatSync: 'BeatSync 引擎',
    toolWordCounter: '字数统计',
    toolImageResizer: '图像调整',
    toolAiUpscaler: 'AI 图像增强',
    toolJsonFormatter: 'JSON 格式化',
    toolPdfMerger: 'PDF 合并',
    toolUnitConverter: '单位转换',
    toolRandomGenerator: '随机生成器',
    toolExcelEngine: 'Excel 数据引擎',
    toolPromptMatrix: '提示矩阵',
    toolDocIntegrity: '文本完整性引擎',
    toolAudioTranscriber: '音频转文字',
    descBgRemover: '使用 AI 即时去除图像背景。',
    descBeatSync: '根据音乐 BPM 和 FPS 计算精确的视频剪切点。',
    descWordCounter: '即时统计单词、字符、句子和段落数量。',
    descImageResizer: '在保持质量的同时将图像调整为精确尺寸。',
    descAiUpscaler: '使用本地 AI 增强图像质量。',
    descJsonFormatter: '使用语法高亮美化、验证和压缩 JSON。',
    descPdfMerger: '将多个 PDF 文件无缝合并为单个文档。',
    descUnitConverter: '在 100 多个长度、重量等单位之间转换。',
    descRandomGenerator: '按需生成密码、UUID 和 lorem ipsum。',
    descExcelEngine: '高效分析、清理和处理电子表格数据。',
    descPromptMatrix: '用于 NPU 模型的神经层次提示工程套件。',
    descDocIntegrity: '进行法证文档比较和文本分析。',
    descAudioTranscriber: '在浏览器中100%本地将任何音频文件转录为干净文本。',
    close: '关闭',
    open: '打开',
    upload: '上传',
    download: '下载',
    clear: '清除',
    copy: '复制',
    copied: '已复制！',
    process: '处理',
    processing: '处理中…',
    reset: '重置',
    generate: '生成',
    merge: '合并',
    convert: '转换',
    analyze: '分析',
    compare: '比较',
    transcribe: '转录',
    remove: '删除',
    format: '格式化',
    beautify: '美化',
    minify: '压缩',
    validate: '验证',
    success: '成功',
    error: '错误',
    loading: '加载中…',
    dragDrop: '将文件拖放到此处',
    or: '或',
    browse: '浏览',
    selectFile: '选择文件',
    noFile: '未选择文件',
    fileReady: '文件已就绪',
    fileSize: '文件大小',
    fileType: '文件类型',
    output: '输出',
    input: '输入',
    result: '结果',
    settings: '设置',
    language: '语言',
  },

  fr: {
    searchPlaceholder: 'Rechercher des outils…',
    searchNoResults: 'Aucun outil trouvé pour',
    allTools: 'Tous les outils',
    catText: 'Texte',
    catImage: 'Image',
    catAudio: 'Audio',
    catVideo: 'Vidéo',
    catCode: 'Code',
    catPDF: 'PDF',
    catUnit: 'Unité',
    catOthers: 'Autres',
    allToolsHeading: 'Tous les outils',
    toolsHeading: 'Outils',
    toolBgRemover: 'Suppresseur de fond IA',
    toolBeatSync: 'Moteur BeatSync',
    toolWordCounter: 'Compteur de mots',
    toolImageResizer: 'Redimensionneur d\'image',
    toolAiUpscaler: 'Améliorateur IA',
    toolJsonFormatter: 'Formateur JSON',
    toolPdfMerger: 'Fusionneur PDF',
    toolUnitConverter: 'Convertisseur d\'unités',
    toolRandomGenerator: 'Générateur aléatoire',
    toolExcelEngine: 'Moteur de données Excel',
    toolPromptMatrix: 'Matrice de prompts',
    toolDocIntegrity: 'Moteur d\'intégrité de texte',
    toolAudioTranscriber: 'Audio en texte',
    descBgRemover: 'Supprimez instantanément les arrière-plans des images avec l\'IA.',
    descBeatSync: 'Calculez les points de coupe vidéo exacts basés sur le BPM et les FPS.',
    descWordCounter: 'Comptez mots, caractères, phrases et paragraphes instantanément.',
    descImageResizer: 'Redimensionnez les images aux dimensions exactes tout en préservant la qualité.',
    descAiUpscaler: 'Améliorez la qualité d\'image avec l\'IA locale.',
    descJsonFormatter: 'Embellissez, validez et minifiez JSON avec coloration syntaxique.',
    descPdfMerger: 'Combinez plusieurs fichiers PDF en un seul document.',
    descUnitConverter: 'Convertissez entre plus de 100 unités de longueur, poids et plus.',
    descRandomGenerator: 'Générez des mots de passe, UUIDs et lorem ipsum à la demande.',
    descExcelEngine: 'Analysez, nettoyez et traitez les données de feuilles de calcul efficacement.',
    descPromptMatrix: 'Suite d\'ingénierie de prompts hiérarchiques neuronaux pour modèles NPU.',
    descDocIntegrity: 'Effectuez une comparaison de documents forensique et une analyse de texte.',
    descAudioTranscriber: 'Transcrivez n\'importe quel fichier audio en texte propre 100% localement.',
    close: 'Fermer',
    open: 'Ouvrir',
    upload: 'Télécharger',
    download: 'Télécharger',
    clear: 'Effacer',
    copy: 'Copier',
    copied: 'Copié !',
    process: 'Traiter',
    processing: 'Traitement…',
    reset: 'Réinitialiser',
    generate: 'Générer',
    merge: 'Fusionner',
    convert: 'Convertir',
    analyze: 'Analyser',
    compare: 'Comparer',
    transcribe: 'Transcrire',
    remove: 'Supprimer',
    format: 'Formater',
    beautify: 'Embellir',
    minify: 'Minifier',
    validate: 'Valider',
    success: 'Succès',
    error: 'Erreur',
    loading: 'Chargement…',
    dragDrop: 'Glissez-déposez le fichier ici',
    or: 'ou',
    browse: 'Parcourir',
    selectFile: 'Sélectionner un fichier',
    noFile: 'Aucun fichier sélectionné',
    fileReady: 'Fichier prêt',
    fileSize: 'Taille du fichier',
    fileType: 'Type de fichier',
    output: 'Sortie',
    input: 'Entrée',
    result: 'Résultat',
    settings: 'Paramètres',
    language: 'Langue',
  },

  de: {
    searchPlaceholder: 'Tools suchen…',
    searchNoResults: 'Keine Tools gefunden für',
    allTools: 'Alle Tools',
    catText: 'Text',
    catImage: 'Bild',
    catAudio: 'Audio',
    catVideo: 'Video',
    catCode: 'Code',
    catPDF: 'PDF',
    catUnit: 'Einheit',
    catOthers: 'Sonstiges',
    allToolsHeading: 'Alle Tools',
    toolsHeading: 'Tools',
    toolBgRemover: 'KI Hintergrundentferner',
    toolBeatSync: 'BeatSync Engine',
    toolWordCounter: 'Wortzähler',
    toolImageResizer: 'Bildgrößenänderer',
    toolAiUpscaler: 'KI Upscaler',
    toolJsonFormatter: 'JSON Formatierer',
    toolPdfMerger: 'PDF Zusammenführer',
    toolUnitConverter: 'Einheitenkonverter',
    toolRandomGenerator: 'Zufallsgenerator',
    toolExcelEngine: 'Excel Daten-Engine',
    toolPromptMatrix: 'Prompt Matrix',
    toolDocIntegrity: 'Text-Integritäts-Engine',
    toolAudioTranscriber: 'Audio zu Text',
    descBgRemover: 'Entfernen Sie Hintergründe von Bildern sofort mit KI.',
    descBeatSync: 'Berechnen Sie genaue Video-Schnittpunkte basierend auf Musik-BPM & FPS.',
    descWordCounter: 'Zählen Sie sofort Wörter, Zeichen, Sätze und Absätze.',
    descImageResizer: 'Ändern Sie die Bildgröße auf genaue Abmessungen bei Qualitätserhalt.',
    descAiUpscaler: 'Verbessern Sie die Bildqualität mit lokaler KI.',
    descJsonFormatter: 'Verschönern, validieren und minifizieren Sie JSON mit Syntaxhervorhebung.',
    descPdfMerger: 'Kombinieren Sie mehrere PDF-Dateien nahtlos in ein Dokument.',
    descUnitConverter: 'Konvertieren Sie zwischen 100+ Einheiten für Länge, Gewicht und mehr.',
    descRandomGenerator: 'Generieren Sie Passwörter, UUIDs und Lorem ipsum auf Anfrage.',
    descExcelEngine: 'Analysieren, bereinigen und verarbeiten Sie Tabellendaten effizient.',
    descPromptMatrix: 'Neuronale hierarchische Prompt-Engineering-Suite für NPU-Modelle.',
    descDocIntegrity: 'Führen Sie forensische Dokumentenvergleiche und Textanalysen durch.',
    descAudioTranscriber: 'Transkribieren Sie jede Audiodatei zu sauberem Text 100% lokal.',
    close: 'Schließen',
    open: 'Öffnen',
    upload: 'Hochladen',
    download: 'Herunterladen',
    clear: 'Löschen',
    copy: 'Kopieren',
    copied: 'Kopiert!',
    process: 'Verarbeiten',
    processing: 'Verarbeitung…',
    reset: 'Zurücksetzen',
    generate: 'Generieren',
    merge: 'Zusammenführen',
    convert: 'Konvertieren',
    analyze: 'Analysieren',
    compare: 'Vergleichen',
    transcribe: 'Transkribieren',
    remove: 'Entfernen',
    format: 'Formatieren',
    beautify: 'Verschönern',
    minify: 'Minifizieren',
    validate: 'Validieren',
    success: 'Erfolg',
    error: 'Fehler',
    loading: 'Lädt…',
    dragDrop: 'Datei hierher ziehen & ablegen',
    or: 'oder',
    browse: 'Durchsuchen',
    selectFile: 'Datei auswählen',
    noFile: 'Keine Datei ausgewählt',
    fileReady: 'Datei bereit',
    fileSize: 'Dateigröße',
    fileType: 'Dateityp',
    output: 'Ausgabe',
    input: 'Eingabe',
    result: 'Ergebnis',
    settings: 'Einstellungen',
    language: 'Sprache',
  },

  es: {
    searchPlaceholder: 'Buscar herramientas…',
    searchNoResults: 'No se encontraron herramientas para',
    allTools: 'Todas las herramientas',
    catText: 'Texto',
    catImage: 'Imagen',
    catAudio: 'Audio',
    catVideo: 'Vídeo',
    catCode: 'Código',
    catPDF: 'PDF',
    catUnit: 'Unidad',
    catOthers: 'Otros',
    allToolsHeading: 'Todas las herramientas',
    toolsHeading: 'Herramientas',
    toolBgRemover: 'Eliminador de fondo IA',
    toolBeatSync: 'Motor BeatSync',
    toolWordCounter: 'Contador de palabras',
    toolImageResizer: 'Redimensionador de imágenes',
    toolAiUpscaler: 'Mejorador IA',
    toolJsonFormatter: 'Formateador JSON',
    toolPdfMerger: 'Fusionador PDF',
    toolUnitConverter: 'Conversor de unidades',
    toolRandomGenerator: 'Generador aleatorio',
    toolExcelEngine: 'Motor de datos Excel',
    toolPromptMatrix: 'Matriz de prompts',
    toolDocIntegrity: 'Motor de integridad de texto',
    toolAudioTranscriber: 'Audio a texto',
    descBgRemover: 'Elimina fondos de imágenes instantáneamente usando IA.',
    descBeatSync: 'Calcula puntos de corte de vídeo exactos basados en BPM y FPS.',
    descWordCounter: 'Cuenta palabras, caracteres, oraciones y párrafos al instante.',
    descImageResizer: 'Redimensiona imágenes a dimensiones exactas preservando la calidad.',
    descAiUpscaler: 'Mejora la calidad de imagen usando IA local.',
    descJsonFormatter: 'Embellece, valida y minifica JSON con resaltado de sintaxis.',
    descPdfMerger: 'Combina múltiples archivos PDF en un solo documento sin problemas.',
    descUnitConverter: 'Convierte entre más de 100 unidades de longitud, peso y más.',
    descRandomGenerator: 'Genera contraseñas, UUIDs y lorem ipsum bajo demanda.',
    descExcelEngine: 'Analiza, limpia y procesa datos de hojas de cálculo eficientemente.',
    descPromptMatrix: 'Suite de ingeniería de prompts jerárquica neuronal para modelos NPU.',
    descDocIntegrity: 'Realiza comparación forense de documentos y análisis de texto.',
    descAudioTranscriber: 'Transcribe cualquier archivo de audio a texto limpio 100% localmente.',
    close: 'Cerrar',
    open: 'Abrir',
    upload: 'Subir',
    download: 'Descargar',
    clear: 'Limpiar',
    copy: 'Copiar',
    copied: '¡Copiado!',
    process: 'Procesar',
    processing: 'Procesando…',
    reset: 'Restablecer',
    generate: 'Generar',
    merge: 'Fusionar',
    convert: 'Convertir',
    analyze: 'Analizar',
    compare: 'Comparar',
    transcribe: 'Transcribir',
    remove: 'Eliminar',
    format: 'Formatear',
    beautify: 'Embellecer',
    minify: 'Minificar',
    validate: 'Validar',
    success: 'Éxito',
    error: 'Error',
    loading: 'Cargando…',
    dragDrop: 'Arrastra y suelta el archivo aquí',
    or: 'o',
    browse: 'Explorar',
    selectFile: 'Seleccionar archivo',
    noFile: 'Ningún archivo seleccionado',
    fileReady: 'Archivo listo',
    fileSize: 'Tamaño del archivo',
    fileType: 'Tipo de archivo',
    output: 'Salida',
    input: 'Entrada',
    result: 'Resultado',
    settings: 'Configuración',
    language: 'Idioma',
  },

  hi: {
    searchPlaceholder: 'टूल्स खोजें…',
    searchNoResults: 'कोई टूल नहीं मिला',
    allTools: 'सभी टूल्स',
    catText: 'पाठ',
    catImage: 'छवि',
    catAudio: 'ऑडियो',
    catVideo: 'वीडियो',
    catCode: 'कोड',
    catPDF: 'PDF',
    catUnit: 'इकाई',
    catOthers: 'अन्य',
    allToolsHeading: 'सभी टूल्स',
    toolsHeading: 'टूल्स',
    toolBgRemover: 'AI बैकग्राउंड रिमूवर',
    toolBeatSync: 'BeatSync इंजन',
    toolWordCounter: 'शब्द गणक',
    toolImageResizer: 'छवि रीसाइज़र',
    toolAiUpscaler: 'AI अपस्केलर',
    toolJsonFormatter: 'JSON फ़ॉर्मेटर',
    toolPdfMerger: 'PDF मर्जर',
    toolUnitConverter: 'इकाई कनवर्टर',
    toolRandomGenerator: 'रैंडम जनरेटर',
    toolExcelEngine: 'Excel डेटा इंजन',
    toolPromptMatrix: 'प्रॉम्प्ट मैट्रिक्स',
    toolDocIntegrity: 'पाठ अखंडता इंजन',
    toolAudioTranscriber: 'ऑडियो से पाठ',
    descBgRemover: 'AI का उपयोग करके छवियों से पृष्ठभूमि तुरंत हटाएं।',
    descBeatSync: 'संगीत BPM और FPS के आधार पर सटीक वीडियो कट पॉइंट्स कैलकुलेट करें।',
    descWordCounter: 'शब्द, अक्षर, वाक्य और पैराग्राफ तुरंत गिनें।',
    descImageResizer: 'गुणवत्ता बनाए रखते हुए छवियों को सटीक आयामों में बदलें।',
    descAiUpscaler: 'स्थानीय AI का उपयोग करके छवि गुणवत्ता बढ़ाएं।',
    descJsonFormatter: 'सिंटैक्स हाइलाइटिंग के साथ JSON को सुंदर, मान्य और छोटा करें।',
    descPdfMerger: 'कई PDF फ़ाइलों को एकल दस्तावेज़ में सहजता से मिलाएं।',
    descUnitConverter: '100 से अधिक लंबाई, वजन इकाइयों के बीच कनवर्ट करें।',
    descRandomGenerator: 'मांग पर पासवर्ड, UUID और lorem ipsum उत्पन्न करें।',
    descExcelEngine: 'स्प्रेडशीट डेटा को कुशलतापूर्वक विश्लेषण, साफ और प्रोसेस करें।',
    descPromptMatrix: 'NPU मॉडलों के लिए न्यूरल पदानुक्रमिक प्रॉम्प्ट इंजीनियरिंग सूट।',
    descDocIntegrity: 'फोरेंसिक दस्तावेज़ तुलना और पाठ विश्लेषण करें।',
    descAudioTranscriber: 'किसी भी ऑडियो फ़ाइल को अपने ब्राउज़र में 100% स्थानीय रूप से साफ पाठ में ट्रांसक्राइब करें।',
    close: 'बंद करें',
    open: 'खोलें',
    upload: 'अपलोड',
    download: 'डाउनलोड',
    clear: 'साफ करें',
    copy: 'कॉपी करें',
    copied: 'कॉपी हो गया!',
    process: 'प्रोसेस करें',
    processing: 'प्रोसेसिंग…',
    reset: 'रीसेट',
    generate: 'उत्पन्न करें',
    merge: 'मर्ज करें',
    convert: 'कनवर्ट करें',
    analyze: 'विश्लेषण करें',
    compare: 'तुलना करें',
    transcribe: 'ट्रांसक्राइब करें',
    remove: 'हटाएं',
    format: 'फ़ॉर्मेट',
    beautify: 'सुंदर बनाएं',
    minify: 'छोटा करें',
    validate: 'सत्यापित करें',
    success: 'सफलता',
    error: 'त्रुटि',
    loading: 'लोड हो रहा है…',
    dragDrop: 'फ़ाइल यहाँ खींचें और छोड़ें',
    or: 'या',
    browse: 'ब्राउज़ करें',
    selectFile: 'फ़ाइल चुनें',
    noFile: 'कोई फ़ाइल नहीं चुनी',
    fileReady: 'फ़ाइल तैयार है',
    fileSize: 'फ़ाइल आकार',
    fileType: 'फ़ाइल प्रकार',
    output: 'आउटपुट',
    input: 'इनपुट',
    result: 'परिणाम',
    settings: 'सेटिंग्स',
    language: 'भाषा',
  },

  pt: {
    searchPlaceholder: 'Pesquisar ferramentas…',
    searchNoResults: 'Nenhuma ferramenta encontrada para',
    allTools: 'Todas as ferramentas',
    catText: 'Texto',
    catImage: 'Imagem',
    catAudio: 'Áudio',
    catVideo: 'Vídeo',
    catCode: 'Código',
    catPDF: 'PDF',
    catUnit: 'Unidade',
    catOthers: 'Outros',
    allToolsHeading: 'Todas as ferramentas',
    toolsHeading: 'Ferramentas',
    toolBgRemover: 'Removedor de fundo IA',
    toolBeatSync: 'Motor BeatSync',
    toolWordCounter: 'Contador de palavras',
    toolImageResizer: 'Redimensionador de imagem',
    toolAiUpscaler: 'Upscaler IA',
    toolJsonFormatter: 'Formatador JSON',
    toolPdfMerger: 'Fusionador PDF',
    toolUnitConverter: 'Conversor de unidades',
    toolRandomGenerator: 'Gerador aleatório',
    toolExcelEngine: 'Motor de dados Excel',
    toolPromptMatrix: 'Matriz de prompts',
    toolDocIntegrity: 'Motor de integridade de texto',
    toolAudioTranscriber: 'Áudio para texto',
    descBgRemover: 'Remova fundos de imagens instantaneamente usando IA.',
    descBeatSync: 'Calcule pontos de corte de vídeo exatos com base no BPM e FPS da música.',
    descWordCounter: 'Conte palavras, caracteres, frases e parágrafos instantaneamente.',
    descImageResizer: 'Redimensione imagens para dimensões exatas preservando a qualidade.',
    descAiUpscaler: 'Melhore a qualidade da imagem usando IA local.',
    descJsonFormatter: 'Embeleze, valide e minifique JSON com destaque de sintaxe.',
    descPdfMerger: 'Combine vários arquivos PDF em um único documento sem problemas.',
    descUnitConverter: 'Converta entre mais de 100 unidades de comprimento, peso e mais.',
    descRandomGenerator: 'Gere senhas, UUIDs e lorem ipsum sob demanda.',
    descExcelEngine: 'Analise, limpe e processe dados de planilhas com eficiência.',
    descPromptMatrix: 'Suite de engenharia de prompt hierárquica neural para modelos NPU.',
    descDocIntegrity: 'Realize comparação forense de documentos e análise de texto.',
    descAudioTranscriber: 'Transcreva qualquer arquivo de áudio para texto limpo 100% localmente.',
    close: 'Fechar',
    open: 'Abrir',
    upload: 'Enviar',
    download: 'Baixar',
    clear: 'Limpar',
    copy: 'Copiar',
    copied: 'Copiado!',
    process: 'Processar',
    processing: 'Processando…',
    reset: 'Redefinir',
    generate: 'Gerar',
    merge: 'Fundir',
    convert: 'Converter',
    analyze: 'Analisar',
    compare: 'Comparar',
    transcribe: 'Transcrever',
    remove: 'Remover',
    format: 'Formatar',
    beautify: 'Embelezar',
    minify: 'Minificar',
    validate: 'Validar',
    success: 'Sucesso',
    error: 'Erro',
    loading: 'Carregando…',
    dragDrop: 'Arraste e solte o arquivo aqui',
    or: 'ou',
    browse: 'Procurar',
    selectFile: 'Selecionar arquivo',
    noFile: 'Nenhum arquivo selecionado',
    fileReady: 'Arquivo pronto',
    fileSize: 'Tamanho do arquivo',
    fileType: 'Tipo de arquivo',
    output: 'Saída',
    input: 'Entrada',
    result: 'Resultado',
    settings: 'Configurações',
    language: 'Idioma',
  },

  ru: {
    searchPlaceholder: 'Поиск инструментов…',
    searchNoResults: 'Инструменты не найдены для',
    allTools: 'Все инструменты',
    catText: 'Текст',
    catImage: 'Изображение',
    catAudio: 'Аудио',
    catVideo: 'Видео',
    catCode: 'Код',
    catPDF: 'PDF',
    catUnit: 'Единица',
    catOthers: 'Прочее',
    allToolsHeading: 'Все инструменты',
    toolsHeading: 'Инструменты',
    toolBgRemover: 'Удаление фона ИИ',
    toolBeatSync: 'Движок BeatSync',
    toolWordCounter: 'Счётчик слов',
    toolImageResizer: 'Изменение размера изображения',
    toolAiUpscaler: 'ИИ Апскейлер',
    toolJsonFormatter: 'Форматировщик JSON',
    toolPdfMerger: 'Объединитель PDF',
    toolUnitConverter: 'Конвертер единиц',
    toolRandomGenerator: 'Генератор случайных данных',
    toolExcelEngine: 'Движок данных Excel',
    toolPromptMatrix: 'Матрица запросов',
    toolDocIntegrity: 'Движок целостности текста',
    toolAudioTranscriber: 'Аудио в текст',
    descBgRemover: 'Мгновенно удаляйте фоны с изображений с помощью ИИ.',
    descBeatSync: 'Вычисляйте точные точки монтажа видео на основе BPM и FPS музыки.',
    descWordCounter: 'Мгновенно считайте слова, символы, предложения и абзацы.',
    descImageResizer: 'Изменяйте размер изображений до точных размеров с сохранением качества.',
    descAiUpscaler: 'Улучшайте качество изображения с помощью локального ИИ.',
    descJsonFormatter: 'Форматируйте, проверяйте и минифицируйте JSON с подсветкой синтаксиса.',
    descPdfMerger: 'Объединяйте несколько файлов PDF в один документ.',
    descUnitConverter: 'Конвертируйте между 100+ единицами длины, веса и другими.',
    descRandomGenerator: 'Генерируйте пароли, UUID и lorem ipsum по запросу.',
    descExcelEngine: 'Эффективно анализируйте, очищайте и обрабатывайте данные таблиц.',
    descPromptMatrix: 'Нейронный иерархический набор инструментов для NPU-моделей.',
    descDocIntegrity: 'Проводите криминалистическое сравнение документов и анализ текста.',
    descAudioTranscriber: 'Транскрибируйте любой аудиофайл в чистый текст 100% локально.',
    close: 'Закрыть',
    open: 'Открыть',
    upload: 'Загрузить',
    download: 'Скачать',
    clear: 'Очистить',
    copy: 'Копировать',
    copied: 'Скопировано!',
    process: 'Обработать',
    processing: 'Обработка…',
    reset: 'Сбросить',
    generate: 'Сгенерировать',
    merge: 'Объединить',
    convert: 'Конвертировать',
    analyze: 'Анализировать',
    compare: 'Сравнить',
    transcribe: 'Транскрибировать',
    remove: 'Удалить',
    format: 'Форматировать',
    beautify: 'Украсить',
    minify: 'Минифицировать',
    validate: 'Проверить',
    success: 'Успех',
    error: 'Ошибка',
    loading: 'Загрузка…',
    dragDrop: 'Перетащите файл сюда',
    or: 'или',
    browse: 'Обзор',
    selectFile: 'Выбрать файл',
    noFile: 'Файл не выбран',
    fileReady: 'Файл готов',
    fileSize: 'Размер файла',
    fileType: 'Тип файла',
    output: 'Вывод',
    input: 'Ввод',
    result: 'Результат',
    settings: 'Настройки',
    language: 'Язык',
  },

  ja: {
    searchPlaceholder: 'ツールを検索…',
    searchNoResults: 'ツールが見つかりません',
    allTools: '全ツール',
    catText: 'テキスト',
    catImage: '画像',
    catAudio: 'オーディオ',
    catVideo: 'ビデオ',
    catCode: 'コード',
    catPDF: 'PDF',
    catUnit: '単位',
    catOthers: 'その他',
    allToolsHeading: '全ツール',
    toolsHeading: 'ツール',
    toolBgRemover: 'AI 背景削除',
    toolBeatSync: 'BeatSync エンジン',
    toolWordCounter: '単語カウンター',
    toolImageResizer: '画像リサイザー',
    toolAiUpscaler: 'AI アップスケーラー',
    toolJsonFormatter: 'JSON フォーマッター',
    toolPdfMerger: 'PDF マージャー',
    toolUnitConverter: '単位変換器',
    toolRandomGenerator: 'ランダムジェネレーター',
    toolExcelEngine: 'Excel データエンジン',
    toolPromptMatrix: 'プロンプトマトリックス',
    toolDocIntegrity: 'テキスト整合性エンジン',
    toolAudioTranscriber: '音声からテキスト',
    descBgRemover: 'AIを使用して画像の背景を即座に削除します。',
    descBeatSync: '音楽のBPMとFPSに基づいて正確なビデオカットポイントを計算します。',
    descWordCounter: '単語、文字、文、段落を即座にカウントします。',
    descImageResizer: '品質を保ちながら画像を正確なサイズに変更します。',
    descAiUpscaler: 'ローカルAIを使用して画像品質を向上させます。',
    descJsonFormatter: 'シンタックスハイライト付きでJSONを整形・検証・圧縮します。',
    descPdfMerger: '複数のPDFファイルをシームレスに1つの文書に結合します。',
    descUnitConverter: '100以上の長さ・重量などの単位を変換します。',
    descRandomGenerator: 'パスワード、UUID、lorem ipsumをオンデマンドで生成します。',
    descExcelEngine: 'スプレッドシートデータを効率的に分析・クリーン・処理します。',
    descPromptMatrix: 'NPUモデル向けニューラル階層プロンプトエンジニアリングスイート。',
    descDocIntegrity: '法的文書比較とテキスト分析を実行します。',
    descAudioTranscriber: '任意の音声ファイルをブラウザで100%ローカルにテキストに変換します。',
    close: '閉じる',
    open: '開く',
    upload: 'アップロード',
    download: 'ダウンロード',
    clear: 'クリア',
    copy: 'コピー',
    copied: 'コピーしました！',
    process: '処理',
    processing: '処理中…',
    reset: 'リセット',
    generate: '生成',
    merge: 'マージ',
    convert: '変換',
    analyze: '分析',
    compare: '比較',
    transcribe: '文字起こし',
    remove: '削除',
    format: 'フォーマット',
    beautify: '整形',
    minify: '圧縮',
    validate: '検証',
    success: '成功',
    error: 'エラー',
    loading: '読み込み中…',
    dragDrop: 'ファイルをここにドラッグ＆ドロップ',
    or: 'または',
    browse: '参照',
    selectFile: 'ファイルを選択',
    noFile: 'ファイルが選択されていません',
    fileReady: 'ファイル準備完了',
    fileSize: 'ファイルサイズ',
    fileType: 'ファイルタイプ',
    output: '出力',
    input: '入力',
    result: '結果',
    settings: '設定',
    language: '言語',
  },

  ko: {
    searchPlaceholder: '도구 검색…',
    searchNoResults: '도구를 찾을 수 없습니다',
    allTools: '모든 도구',
    catText: '텍스트',
    catImage: '이미지',
    catAudio: '오디오',
    catVideo: '비디오',
    catCode: '코드',
    catPDF: 'PDF',
    catUnit: '단위',
    catOthers: '기타',
    allToolsHeading: '모든 도구',
    toolsHeading: '도구',
    toolBgRemover: 'AI 배경 제거',
    toolBeatSync: 'BeatSync 엔진',
    toolWordCounter: '단어 카운터',
    toolImageResizer: '이미지 리사이저',
    toolAiUpscaler: 'AI 업스케일러',
    toolJsonFormatter: 'JSON 포매터',
    toolPdfMerger: 'PDF 병합기',
    toolUnitConverter: '단위 변환기',
    toolRandomGenerator: '랜덤 생성기',
    toolExcelEngine: 'Excel 데이터 엔진',
    toolPromptMatrix: '프롬프트 매트릭스',
    toolDocIntegrity: '텍스트 무결성 엔진',
    toolAudioTranscriber: '오디오를 텍스트로',
    descBgRemover: 'AI를 사용하여 이미지에서 배경을 즉시 제거합니다.',
    descBeatSync: '음악 BPM 및 FPS를 기반으로 정확한 비디오 컷 포인트를 계산합니다.',
    descWordCounter: '단어, 문자, 문장 및 단락을 즉시 셉니다.',
    descImageResizer: '품질을 유지하면서 이미지를 정확한 크기로 조정합니다.',
    descAiUpscaler: '로컬 AI를 사용하여 이미지 품질을 향상시킵니다.',
    descJsonFormatter: '구문 강조 표시와 함께 JSON을 정렬, 검증 및 압축합니다.',
    descPdfMerger: '여러 PDF 파일을 하나의 문서로 원활하게 결합합니다.',
    descUnitConverter: '100개 이상의 길이, 무게 등 단위 간 변환합니다.',
    descRandomGenerator: '요청 시 비밀번호, UUID 및 lorem ipsum을 생성합니다.',
    descExcelEngine: '스프레드시트 데이터를 효율적으로 분석, 정리 및 처리합니다.',
    descPromptMatrix: 'NPU 모델을 위한 신경 계층적 프롬프트 엔지니어링 스위트.',
    descDocIntegrity: '법의학적 문서 비교 및 텍스트 분석을 수행합니다.',
    descAudioTranscriber: '모든 오디오 파일을 브라우저에서 100% 로컬로 텍스트로 변환합니다.',
    close: '닫기',
    open: '열기',
    upload: '업로드',
    download: '다운로드',
    clear: '지우기',
    copy: '복사',
    copied: '복사됨!',
    process: '처리',
    processing: '처리 중…',
    reset: '초기화',
    generate: '생성',
    merge: '병합',
    convert: '변환',
    analyze: '분석',
    compare: '비교',
    transcribe: '변환',
    remove: '제거',
    format: '형식',
    beautify: '정렬',
    minify: '압축',
    validate: '검증',
    success: '성공',
    error: '오류',
    loading: '로딩 중…',
    dragDrop: '파일을 여기에 드래그 앤 드롭',
    or: '또는',
    browse: '찾아보기',
    selectFile: '파일 선택',
    noFile: '파일이 선택되지 않았습니다',
    fileReady: '파일 준비 완료',
    fileSize: '파일 크기',
    fileType: '파일 유형',
    output: '출력',
    input: '입력',
    result: '결과',
    settings: '설정',
    language: '언어',
  },
};

/* ─── Context ─────────────────────────────────────────────────── */
interface LanguageContextType {
  lang: LangCode;
  setLang: (code: LangCode) => void;
  t: Translations;
  currentLang: Language;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'en',
  setLang: () => {},
  t: translations.en,
  currentLang: LANGUAGES[0],
  isRTL: false,
});

/* ─── Provider ────────────────────────────────────────────────── */
export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<LangCode>('en');

  useEffect(() => {
    const saved = localStorage.getItem('app-language') as LangCode | null;
    if (saved && translations[saved]) {
      setLangState(saved);
      applyRTL(saved);
    }
  }, []);

  const applyRTL = (code: LangCode) => {
    const isRTL = LANGUAGES.find(l => l.code === code)?.rtl ?? false;
    document.documentElement.setAttribute('dir', isRTL ? 'rtl' : 'ltr');
    document.documentElement.setAttribute('lang', code);
  };

  const setLang = (code: LangCode) => {
    setLangState(code);
    localStorage.setItem('app-language', code);
    applyRTL(code);
  };

  const currentLang = LANGUAGES.find(l => l.code === lang) ?? LANGUAGES[0];
  const isRTL = currentLang.rtl;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t: translations[lang], currentLang, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

/* ─── Hook ────────────────────────────────────────────────────── */
export function useLanguage() {
  return useContext(LanguageContext);
}
